service: sparcs-certificate-service

custom:
  projectName: sparcs-events
  serviceName: certificate-generator
  stage: ${opt:stage, self:provider.stage}
  entities: ${self:custom.stage}-${self:custom.projectName}-entities
  bucket: ${self:custom.stage}-${self:custom.projectName}-file-bucket
  registrations: ${self:custom.stage}-${self:custom.projectName}-registrations
  certificateQueue: ${self:custom.stage}-${self:custom.projectName}-certificate-queue.fifo
  logRetentionInDays: 30

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 3008
  versionFunctions: false
  architecture: x86_64
  ecr:
    images:
      generate_certificate:
        path: ./
        platform: linux/amd64
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    CERTIFICATE_QUEUE: ${self:custom.certificateQueue}
    REGISTRATIONS_TABLE: ${self:custom.registrations}
    ENTITIES_TABLE: ${self:custom.entities}
    S3_BUCKET: ${self:custom.bucket}

package: ${file(resources/package.yml)}

resources:
  - ${file(resources/sqs.yml)}

functions:
  - ${file(resources/generate_certificate.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
