patterns:
  - "setup/**"
  - "!**/.git/**"
  - "!**/.idea/**"
  - "!**/.pytest_cache/**"
  - "!**/.serverless/**"
  - "!**/__pycache__/**"
  - "!htmlcov/**"
  - "!node_modules/**"
  - "!assets/**"
  - "!resources/**"
  - "!test/**"
  - "!scripts/**"
  - "!layers/**"
  - "!*.coverage"
  - "!*.coveragerc"
  - "!*.gitignore"
  - "!buildspec.yml"
  - "!package.json"
  - "!package-lock.json"
  - "!Pipfile"
  - "!Pipfile.lock"
  - "!pytest.ini"
  - "!README.md"
  - "!serverless.yml"
  - "!bitbucket-pipelines.yml"
  - "!.pylintrc"
  - "!PRE-COMMIT.md"
  - ".isort.cfg"
