Resources:
  CertificateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.certificateQueue}
      FifoQueue: true
      MessageRetentionPeriod: 86400 # 1 day
      VisibilityTimeout: 900
      ReceiveMessageWaitTimeSeconds: 20

  CertificateQueueSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sparcs-events-certificate-queue-url-${self:custom.stage}
      Type: String
      Value: !Ref CertificateQueue

Outputs:
  CertificateQueueUrl:
    Value: !Ref CertificateQueue
    Export:
      Name: CertificateQueue-${self:custom.stage}
